const images = {
  icons: {
    otp_outline: require('../../assets/images/icons/otp-outline.png'),
    phone: require('../../assets/images/icons/phone.png'),
    key: require('../../assets/images/icons/key.png'),
    name: require('../../assets/images/icons/name.png'),
    close: require('../../assets/images/icons/close.png'),
    qr_code: require('../../assets/images/icons/qr-code.png'),
    select_avatar: require('../../assets/images/icons/select-avatar.png'),
    time: require('../../assets/images/icons/time.png'),
    bt_home: require('../../assets/images/icons/home.png'),
    bt_control: require('../../assets/images/icons/control.png'),
    bt_location: require('../../assets/images/icons/location.png'),
    bt_account: require('../../assets/images/icons/account.png'),
    bt_setting: require('../../assets/images/icons/setting.png'),
    header_plus: require('../../assets/images/icons/plus.png'),
    input_search: require('../../assets/images/icons/search.png'),
    nav_back: require('../../assets/images/icons/nav_back.png'),
    camera: require('../../assets/images/icons/camera.png'),
    capture_white_plus: require('../../assets/images/icons/capture-white-plus.png'),
    date: require('../../assets/images/icons/date.png'),
    refresh: require('../../assets/images/icons/refresh.png'),
    wrapCalendar: require('../../assets/images/icons/wrap-calendar.png'),
    filter: require('../../assets/images/icons/filter.png'),
    info_manager: require('../../assets/images/icons/icon_account_info.png'),
    safe_web: require('../../assets/images/icons/icon_web_safe.png'),
    safe_search: require('../../assets/images/icons/icon_safe_search.png'),
    edit: require('../../assets/images/icons/edit.png'),
    web_default: require('../../assets/images/icons/web_default.jpg'),
    area_chart_total: require('../../assets/images/icons/area_chart_total.png'),
    area_filter: require('../../assets/images/icons/area_filter.png'),
    area_safe_search: require('../../assets/images/icons/area_safe_search.png'),
    lock_location: require('../../assets/images/icons/lock_location.png'),
    game: require('../../assets/images/icons/game.png'),
    gender: require('../../assets/images/icons/gender.png'),
    ads: require('../../assets/images/icons/ads.png'),
    question: require('../../assets/images/icons/question.png'),
  },
  avatars: {
    default: require('../../assets/images/avatars/default.jpeg'),
    picture_default: require('../../assets/images/avatars/picture_default.png'),
    shield: require('../../assets/images/avatars/shield.png'),
  },
  backgrounds: {
    background_in: require('../../assets/images/backgrounds/background-in.png'),
    background_out: require('../../assets/images/backgrounds/background-out.png'),
    error_500: require('../../assets/images/backgrounds/error_500.png'),
    error_401: require('../../assets/images/backgrounds/error_401.png'),
    disconnect: require('../../assets/images/backgrounds/disconnect.png'),
  },
  logos: {
    main: require('../../assets/images/logos/main.png'),
    success: require('../../assets/images/logos/success.png'),
    error: require('../../assets/images/logos/error.png'),
    lock: require('../../assets/images/logos/lock.png'),
    activated_lock: require('../../assets/images/logos/activated_lock.png'),
  },
};

export default images;
