const colors = {
  COLOR_PRIMARY: '#2ec7ab',
  COLOR_SECONDARY: '#111',
  COLOR_WHITE: '#FFFFFF',
  COLOR_BLACK: '#000000',
  COLOR_GREY: 'grey',
  COLOR_GREEN: '#20F167',
  COLOR_PLACEHOLDER: '#888888',
  COLOR_GREY_WHITE: '#fafafa',
  COLOR_DARK_SEPERATOR: '#d4d4d4',
  COLOR_BLACK_TRANSP: 'rgba(0, 0, 0, 0.7)',
  COLOR_GREY_TRANSP: 'rgba(67, 85, 85, 0.7)',
  COLOR_BLUE: '#5A8ED1',
  COLOR_RED_ORANGE: '#FF655B',
  COLOR_RED: '#FF0000',
  COLOR_PINK: '#F178B6',
  COLOR_DARK_BLUE: '#1A2246',
  COLOR_UNDERLAY_BLUE: '#2466BA',
  COLOR_UNDERLAY_BUTTON_BACK: '#47A2DF',
  COLOR_UNDERLAY_BUTTON_PINK: '#E41D83',
  COLOR_UNDERLAY_BUTTON_RED: '#D22E24',
  COLOR_UNDERLAY_BUTTON_WHITE: '#D8D8D8',
  COLOR_UNDERLAY_BUTTON_BLACK: '#dcdcdc',
  COLOR_ERROR: '#FF655B',
  COLOR_DISABLE: '#AAAAAA',

  //chart
  COLOR_CHART_BLUE: '#1199D3',
  COLOR_CHART_YELLOW: '#D3C011',
};

export default colors;
