const fonts = {
  lexendDeca: {
    FONT_REGULAR: 'LexendDeca-Regular',
    FONT_BLACK: 'LexendDeca-Black',
    FONT_LIGHT: 'LexendDeca-Light',
    FONT_EXTRA_LIGHT: 'LexendDeca-ExtraLight',
    FONT_THIN: 'LexendDeca-Thin',
    FONT_MEDIUM: 'LexendDeca-Medium',
    FONT_SEMI_BOLD: 'LexendDeca-SemiBold',
    FONT_BOLD: 'LexendDeca-Bold',
    FONT_EXTRA_BOLD: 'LexendDeca-ExtraBold',
  },
  montserrat: {
    FONT_REGULAR: 'Montserrat-Regular',
    FONT_ITALIC: 'Montserrat-Italic',
    FONT_THIN: 'Montserrat-Thin',
    FONT_THIN_ITALIC: 'Montserrat-ThinItalic',
    FONT_EXTRA_LIGHT: 'Montserrat-ExtraLight',
    FONT_EXTRA_LIGHT_ITALIC: 'Montserrat-ExtraLightItalic',
    FONT_LIGHT: 'Montserrat-Light',
    FONT_LIGHT_ITALIC: 'Montserrat-LightItalic',
    FONT_MEDIUM: 'Montserrat-Medium',
    FONT_MEDIUM_ITALIC: 'Montserrat-MediumItalic',
    FONT_SEMI_BOLD: 'Montserrat-SemiBold',
    FONT_SEMI_BOLD_ITALIC: 'Montserrat-SemiBoldItalic',
    FONT_BOLD: 'Montserrat-Bold',
    FONT_BOLD_ITALIC: 'Montserrat-BoldItalic',
    FONT_EXTRA_BOLD: 'Montserrat-ExtraBold',
    FONT_EXTRA_BOLD_ITALIC: 'Montserrat-ExtraBoldItalic',
    FONT_BLACK: 'Montserrat-Black',
    FONT_BLACK_ITALIC: 'Montserrat-BlackItalic',
  },
};

export default fonts;
