require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'SafeZone' do
  
  config = use_native_modules!
  rn_maps_path = '../node_modules/react-native-maps'
  pod '@react-native-mapbox-gl-mapbox-static', '~> 10.0.0-beta.12'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'Google-Maps-iOS-Utils'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
 
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )
  

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

  target 'SafeZoneTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  

  # post_install do |installer|
  #   $RNMapboxMaps.post_install(installer)
  # end

  # def find_and_replace(dir, findstr, replacestr)
  #   Dir[dir].each do |name|
  #       text = File.read(name)
  #       replace = text.gsub(findstr,replacestr)
  #       if text != replace
  #           puts "Fix: " + name
  #           File.open(name, "w") { |file| file.puts replace }
  #           STDOUT.flush
  #       end
  #   end
  #   Dir[dir + '*/'].each(&method(:find_and_replace))
  # end
  post_install do |installer|
    $RNMBGL.post_install(installer)
    # ... other post install hooks
  end
end