export default {
  login: 'LOGIN',
  //device
  DEVICE_LIST: 'DEVICE_LIST',
  DEVICE_LIST_MANAGER: 'DEVICE_LIST_MANAGER',
  DEVICE_LIST_LOCATION: 'DEVICE_LIST_LOCATION',
  DEVICE_INFO: 'DEVICE_INFO',
  DEVICE_HISTORY_LIST: 'DEVICE_HISTORY_LIST',
  DEVICE_SETTING_LIST: 'DEVICE_SETTING_LIST',

  //web
  WEB_REPORT_ACCESS: 'WEB_REPORT_ACCESS',
  WEB_LIST: 'WEB_LIST',

  //application
  APPLICATION_LIST: 'APPLICATION_LIST',
};
