export default {
  login: 'LOGIN',
  WEB_LIST: 'WEB_LIST',
  DEVICE_LIST: 'DEVICE_LIST',
  DEVICE_INFO: 'DEVICE_INFO',
  DEVICE_REPORT_LIST: 'DEVICE_REPORT_LIST',
  DEVICE_HISTORY_LIST: 'DEVICE_HISTORY_LIST',

  //application
  APPLICATION_LIST: 'APPLICATION_LIST',
};
