export default {
  login: 'LOGIN',
  web_list: 'WEB_LIST',
  DEVICE_LIST: 'DEVICE_LIST',
  DEVICE_INFO: 'DEVICE_INFO',
  DEVICE_REPORT_LIST: 'DEVICE_REPORT_LIST',
  DEVICE_HISTORY_LIST: 'DEVICE_HISTORY_LIST',
};
