# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    # crashlytics
    firebase_app_distribution(
      firebase_cli_token: '1//0e6R0jL8Y5glTCgYIARAAGA4SNwF-L9IrmyaUL3OdH3brhN1w9mJxnVhF0RJ4swsUj32Lg731wl2Wn41mW456eQrKRPC2GctDwBU',
      app: "1:300663446423:android:0640608fd9343cf7b9c2d2",
      release_notes: "
        Thêm tính năng thiết lập chặn ở màn hình thông tin thiết bị
        Thêm tính năng bật tắt cài đặt thời gian cho thiết bị, ứng dụng, website
      ",
      testers: "ngoquyen45@gmail.com",
      debug: true
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
